name = "PGENFiles"
uuid = "bbb59ef6-f40c-4dde-a38e-7e7eb74f31f9"
authors = ["Seyoon Ko <kos@ucla.edu> and contributors"]
version = "0.1.0"

[deps]
BitIntegers = "c3b6d118-76ef-56ca-8cc7-ebb389d030a1"
Mmap = "a63ad114-7e13-5084-954f-fe012c677804"

[compat]
BitIntegers = "0.2"
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
